version: "3.1"
services:
  aura-api:
    container_name: aura-api
    image: ghcr.io/adm-metaex/aura-api:v0.0.1-b944b0b
    restart: always
    tty: true
    ports:
      - "${API_PORT}:${API_PORT}"
      - "${API_SWAGGER_PORT}:${API_SWAGGER_PORT}"
    volumes:
      - ./creds/API_CERT_FILE:/creds/API_CERT_FILE:ro
    env_file:
      - .env
    command:
      - -log=debug
    logging:
      options:
        max-size: "1g"
