---
services:
  aura-api:
    container_name: aura-api
    image: ghcr.io/adm-metaex/aura-api:develop-6aa1bd8
    restart: unless-stopped
    #    entrypoint: "sleep 600"
    tty: true
    ports:
      - "${API_PORT}:${API_PORT}"
      - "${API_SWAGGER_PORT}:${API_SWAGGER_PORT}"
    volumes:
      - ./creds/API_CERT_FILE:/creds/API_CERT_FILE:ro
      - ./ssl:/ssl
    env_file:
      - .env
    environment:
      HOST_HOSTNAME: "${HOST_HOSTNAME}"
    command:
      - -log=debug
    logging:
      options:
        max-size: "1g"
    networks:
      - aura-gw
    labels:
      - aura-gw=healthy
  aura-stats-api:
    container_name: aura-stats-api
    image: ghcr.io/adm-metaex/aura-statsapi:develop-6aa1bd8
    restart: unless-stopped
    tty: true
    ports:
      - "${STATS_API_PORT}:${STATS_API_PORT}"
      - "${STATS_API_SWAGGER_PORT}:${STATS_API_SWAGGER_PORT}"
    volumes:
      - ./creds/API_CERT_FILE:/creds/API_CERT_FILE:ro
      - ./ssl:/ssl
    env_file:
      - .env
    environment:
      HOST_HOSTNAME: "${HOST_HOSTNAME}"
    command:
      - -log=debug
    logging:
      options:
        max-size: "1g"
    networks:
      - aura-gw
    labels:
      - aura-gw=healthy
networks:
  aura-gw:
    driver: bridge
    name: aura-gw
