// Package docs Code generated by swaggo/swag at 2024-12-16 18:27:26.520573445 +0200 EET m=+0.014266212. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/keys": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get api keys for user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api key"
                ],
                "summary": "Get api keys for user",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Define if we need to show deleted keys. If the parameter is not present - show only living keys. If show_deleted == true only deleted keys will be returned. If show_deleted == false all keys (living and deleted) will be returned",
                        "name": "show_deleted",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/postgres.APIKeyWithSupportedNetworks"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create api key",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api key"
                ],
                "summary": "Create api key",
                "parameters": [
                    {
                        "description": "API key creation request",
                        "name": "request_body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateAPIKeyRequestParams"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/postgres.APIKeyWithSupportedNetworks"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/keys/{token}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get api key by token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api key"
                ],
                "summary": "Get api key by token",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "example": "98379b6b-dc6a-4d8e-8271-12eed4822afc",
                        "description": "Token parameter",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/postgres.APIKeyWithSupportedNetworks"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete api key",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api key"
                ],
                "summary": "Delete api key",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "example": "98379b6b-dc6a-4d8e-8271-12eed4822afc",
                        "description": "Token parameter",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Api key was deleted successfully. Return empty string",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update api key",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api key"
                ],
                "summary": "Update api key",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "example": "98379b6b-dc6a-4d8e-8271-12eed4822afc",
                        "description": "Token parameter",
                        "name": "token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "API key update request",
                        "name": "request_body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateAPIKeyRequestParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/postgres.APIKeyWithSupportedNetworks"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/networks": {
            "get": {
                "description": "Return list of supported networks",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "networks"
                ],
                "summary": "Get list of supported networks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/plans": {
            "get": {
                "description": "Get subscriptions plan info",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "networks"
                ],
                "summary": "Get subscriptions plan info",
                "responses": {
                    "200": {
                        "description": "If there is no monthly_price_mplx in response - it is Pay As You Go plan and we need to use price_mplx inside each pricing. If monthly_price_mplx present - we need to use it",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.SubscriptionWithPricing"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/stats/credits/usage": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get user credits usage",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Get user credits usage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Request granularity (1 candle size). Can be either 1d (1 day) or 1h (1 hour)",
                        "name": "granularity",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request timeframe. Can be one of the following: [1h, 4h, 12h, 1d, 7d, 14d, 30d]",
                        "name": "timeframe",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "example": "98379b6b-dc6a-4d8e-8271-12eed4822afc",
                        "description": "User api token",
                        "name": "token",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Network where requests were executed",
                        "name": "network",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RPC method. If indicated, require paas network parameter too",
                        "name": "method",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/clickhouse.CreditsUsageHistory"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/stats/request/volume": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get user requests volume",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Get user requests volume",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Request granularity (1 candle size). Can be either 1d (1 day) or 1h (1 hour)",
                        "name": "granularity",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request timeframe. Can be one of the following: [1h, 4h, 12h, 1d, 7d, 14d, 30d]",
                        "name": "timeframe",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "example": "98379b6b-dc6a-4d8e-8271-12eed4822afc",
                        "description": "User api token",
                        "name": "token",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Network where requests were executed",
                        "name": "network",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RPC method. If indicated, require paas network parameter too",
                        "name": "method",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/clickhouse.RequestsVolumeHistory"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/stats/response/time": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get response time history (avg \u0026\u0026 p95) for user requests",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Get response time history (avg \u0026\u0026 p95) for user requests",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Request granularity (1 candle size). Can be either 1d (1 day) or 1h (1 hour)",
                        "name": "granularity",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Request timeframe. Can be one of the following: [1h, 4h, 12h, 1d, 7d, 14d, 30d]",
                        "name": "timeframe",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "example": "98379b6b-dc6a-4d8e-8271-12eed4822afc",
                        "description": "User api token",
                        "name": "token",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Network where requests were executed",
                        "name": "network",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RPC method. If indicated, require paas network parameter too",
                        "name": "method",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/clickhouse.ResponseTimeHistory"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/user": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Return object with user info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "api.CreateAPIKeyRequestParams": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "networks": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "Aura",
                            " Solana"
                        ]
                    }
                }
            }
        },
        "api.Pricing": {
            "type": "object",
            "properties": {
                "api_tokens_limit": {
                    "type": "integer"
                },
                "aura_das": {
                    "$ref": "#/definitions/api.UIPricing"
                },
                "eclipse_das": {
                    "$ref": "#/definitions/api.UIPricing"
                },
                "eclipse_rpc": {
                    "$ref": "#/definitions/api.UIPricing"
                },
                "get_program_accounts": {
                    "$ref": "#/definitions/api.UIPricing"
                },
                "monthly_price_mplx": {
                    "type": "number"
                },
                "solana_rpc": {
                    "$ref": "#/definitions/api.UIPricing"
                },
                "solana_swqos": {
                    "$ref": "#/definitions/api.UIPricing"
                },
                "websocket": {
                    "$ref": "#/definitions/api.UIPricing"
                }
            }
        },
        "api.SubscriptionWithPricing": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "pricing": {
                    "$ref": "#/definitions/api.Pricing"
                },
                "priority": {
                    "type": "integer"
                }
            }
        },
        "api.UIPricing": {
            "type": "object",
            "properties": {
                "price_mplx": {
                    "type": "number"
                },
                "requests_per_second": {
                    "type": "integer"
                }
            }
        },
        "api.UpdateAPIKeyRequestParams": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "x-nullable": true
                },
                "networks": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "Aura",
                            " Solana"
                        ]
                    }
                }
            }
        },
        "api.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "dynamic_id": {
                    "type": "string"
                },
                "mplx_balance": {
                    "type": "integer"
                },
                "subscription": {
                    "$ref": "#/definitions/postgres.Plan"
                }
            }
        },
        "clickhouse.CreditsUsageHistory": {
            "type": "object",
            "properties": {
                "networks": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "clickhouse.RequestsVolumeHistory": {
            "type": "object",
            "properties": {
                "network": {
                    "type": "string"
                },
                "rpc_method": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "total_errors": {
                    "type": "integer"
                },
                "total_requests": {
                    "type": "integer"
                }
            }
        },
        "clickhouse.ResponseTimeHistory": {
            "type": "object",
            "properties": {
                "avg_response_time_ms": {
                    "type": "integer"
                },
                "network": {
                    "type": "string"
                },
                "p95_response_time_ms": {
                    "type": "integer"
                },
                "rpc_method": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "postgres.APIKeyWithSupportedNetworks": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "last_used": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "supported_networks": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "token": {
                    "type": "string"
                },
                "total_requests": {
                    "type": "integer"
                }
            }
        },
        "postgres.Plan": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "token_limit": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Bearer JWT",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.2",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Swagger Aura",
	Description:      "Swagger API server for Aura API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}
