basePath: /
consumes:
- application/json
definitions:
  api.CreateAPIKeyRequestParams:
    properties:
      name:
        type: string
      networks:
        items:
          enum:
          - Aura
          - ' Solana'
          type: string
        type: array
    type: object
  api.UpdateAPIKeyRequestParams:
    properties:
      name:
        type: string
        x-nullable: true
      networks:
        items:
          enum:
          - Aura
          - ' Solana'
          type: string
        type: array
    type: object
  api.User:
    properties:
      created_at:
        type: string
      dynamic_id:
        type: string
      mplx_balance:
        type: integer
      subscription:
        $ref: '#/definitions/postgres.Subscription'
    type: object
  clickhouse.CreditsUsageHistory:
    properties:
      networks:
        additionalProperties:
          type: integer
        type: object
      timestamp:
        type: string
    type: object
  clickhouse.RequestsVolumeHistory:
    properties:
      network:
        type: string
      rpc_method:
        type: string
      timestamp:
        type: string
      token:
        type: string
      total_errors:
        type: integer
      total_requests:
        type: integer
    type: object
  clickhouse.ResponseTimeHistory:
    properties:
      avg_response_time_ms:
        type: integer
      network:
        type: string
      p95_response_time_ms:
        type: integer
      rpc_method:
        type: string
      timestamp:
        type: string
      token:
        type: string
    type: object
  postgres.APIKeyWithSupportedNetworks:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      last_used:
        type: string
      name:
        type: string
      supported_networks:
        items:
          type: string
        type: array
      token:
        type: string
      total_requests:
        type: integer
    type: object
  postgres.Subscription:
    properties:
      minimum_balance:
        type: integer
      name:
        type: string
      requests_per_second:
        type: integer
      token_limit:
        type: integer
    type: object
info:
  contact: {}
  description: Swagger API server for Aura API.
  termsOfService: http://swagger.io/terms/
  title: Swagger Aura
  version: 0.0.2
paths:
  /keys:
    get:
      consumes:
      - application/json
      description: Get api keys for user
      parameters:
      - description: Define if we need to show deleted keys. If the parameter is not
          present - show only living keys. If show_deleted == true only deleted keys
          will be returned. If show_deleted == false all keys (living and deleted)
          will be returned
        in: query
        name: show_deleted
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/postgres.APIKeyWithSupportedNetworks'
            type: array
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Get api keys for user
      tags:
      - api key
    post:
      consumes:
      - application/json
      description: Create api key
      parameters:
      - description: API key creation request
        in: body
        name: request_body
        required: true
        schema:
          $ref: '#/definitions/api.CreateAPIKeyRequestParams'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/postgres.APIKeyWithSupportedNetworks'
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Create api key
      tags:
      - api key
  /keys/{token}:
    delete:
      consumes:
      - application/json
      description: Delete api key
      parameters:
      - description: Token parameter
        example: 98379b6b-dc6a-4d8e-8271-12eed4822afc
        format: uuid
        in: path
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Api key was deleted successfully. Return empty string
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Delete api key
      tags:
      - api key
    get:
      consumes:
      - application/json
      description: Get api key by token
      parameters:
      - description: Token parameter
        example: 98379b6b-dc6a-4d8e-8271-12eed4822afc
        format: uuid
        in: path
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/postgres.APIKeyWithSupportedNetworks'
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Get api key by token
      tags:
      - api key
    patch:
      consumes:
      - application/json
      description: Update api key
      parameters:
      - description: Token parameter
        example: 98379b6b-dc6a-4d8e-8271-12eed4822afc
        format: uuid
        in: path
        name: token
        required: true
        type: string
      - description: API key update request
        in: body
        name: request_body
        required: true
        schema:
          $ref: '#/definitions/api.UpdateAPIKeyRequestParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/postgres.APIKeyWithSupportedNetworks'
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Update api key
      tags:
      - api key
  /networks:
    get:
      description: Return list of supported networks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get list of supported networks
      tags:
      - networks
  /stats/credits/usage:
    get:
      description: Get user credits usage
      parameters:
      - description: Request granularity (1 candle size). Can be either 1d (1 day)
          or 1h (1 hour)
        in: query
        name: granularity
        required: true
        type: string
      - description: 'Request timeframe. Can be one of the following: [1h, 4h, 12h,
          1d, 7d, 14d, 30d]'
        in: query
        name: timeframe
        required: true
        type: string
      - description: User api token
        example: 98379b6b-dc6a-4d8e-8271-12eed4822afc
        format: uuid
        in: query
        name: token
        type: string
      - description: Network where requests were executed
        in: query
        name: network
        type: string
      - description: RPC method. If indicated, require paas network parameter too
        in: query
        name: method
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/clickhouse.CreditsUsageHistory'
            type: array
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Get user credits usage
      tags:
      - stats
  /stats/request/volume:
    get:
      description: Get user requests volume
      parameters:
      - description: Request granularity (1 candle size). Can be either 1d (1 day)
          or 1h (1 hour)
        in: query
        name: granularity
        required: true
        type: string
      - description: 'Request timeframe. Can be one of the following: [1h, 4h, 12h,
          1d, 7d, 14d, 30d]'
        in: query
        name: timeframe
        required: true
        type: string
      - description: User api token
        example: 98379b6b-dc6a-4d8e-8271-12eed4822afc
        format: uuid
        in: query
        name: token
        type: string
      - description: Network where requests were executed
        in: query
        name: network
        type: string
      - description: RPC method. If indicated, require paas network parameter too
        in: query
        name: method
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/clickhouse.RequestsVolumeHistory'
            type: array
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Get user requests volume
      tags:
      - stats
  /stats/response/time:
    get:
      description: Get response time history (avg && p95) for user requests
      parameters:
      - description: Request granularity (1 candle size). Can be either 1d (1 day)
          or 1h (1 hour)
        in: query
        name: granularity
        required: true
        type: string
      - description: 'Request timeframe. Can be one of the following: [1h, 4h, 12h,
          1d, 7d, 14d, 30d]'
        in: query
        name: timeframe
        required: true
        type: string
      - description: User api token
        example: 98379b6b-dc6a-4d8e-8271-12eed4822afc
        format: uuid
        in: query
        name: token
        type: string
      - description: Network where requests were executed
        in: query
        name: network
        type: string
      - description: RPC method. If indicated, require paas network parameter too
        in: query
        name: method
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/clickhouse.ResponseTimeHistory'
            type: array
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Get response time history (avg && p95) for user requests
      tags:
      - stats
  /user:
    get:
      consumes:
      - application/json
      description: Return object with user info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.User'
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Get user info
      tags:
      - users
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    description: Bearer JWT
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
