// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.4
// source: pkg/proto/aura.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Aura_BatchInsertStats_FullMethodName     = "/proto.Aura/BatchInsertStats"
	Aura_IncreaseUserRequests_FullMethodName = "/proto.Aura/IncreaseUserRequests"
	Aura_GetAllUsers_FullMethodName          = "/proto.Aura/GetAllUsers"
	Aura_GetUserInfo_FullMethodName          = "/proto.Aura/GetUserInfo"
	Aura_GetSubscriptions_FullMethodName     = "/proto.Aura/GetSubscriptions"
)

// AuraClient is the client API for Aura service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuraClient interface {
	// ClickHouse
	BatchInsertStats(ctx context.Context, in *BatchInsertStatsReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	IncreaseUserRequests(ctx context.Context, in *IncreaseUserRequestsReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// PosgreSQL
	GetAllUsers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetUserInfoResp], error)
	GetUserInfo(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GetUserInfoReq, GetUserInfoResp], error)
	GetSubscriptions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSubscriptionsResp, error)
}

type auraClient struct {
	cc grpc.ClientConnInterface
}

func NewAuraClient(cc grpc.ClientConnInterface) AuraClient {
	return &auraClient{cc}
}

func (c *auraClient) BatchInsertStats(ctx context.Context, in *BatchInsertStatsReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Aura_BatchInsertStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auraClient) IncreaseUserRequests(ctx context.Context, in *IncreaseUserRequestsReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Aura_IncreaseUserRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auraClient) GetAllUsers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetUserInfoResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Aura_ServiceDesc.Streams[0], Aura_GetAllUsers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, GetUserInfoResp]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Aura_GetAllUsersClient = grpc.ServerStreamingClient[GetUserInfoResp]

func (c *auraClient) GetUserInfo(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GetUserInfoReq, GetUserInfoResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Aura_ServiceDesc.Streams[1], Aura_GetUserInfo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetUserInfoReq, GetUserInfoResp]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Aura_GetUserInfoClient = grpc.BidiStreamingClient[GetUserInfoReq, GetUserInfoResp]

func (c *auraClient) GetSubscriptions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSubscriptionsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubscriptionsResp)
	err := c.cc.Invoke(ctx, Aura_GetSubscriptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuraServer is the server API for Aura service.
// All implementations must embed UnimplementedAuraServer
// for forward compatibility.
type AuraServer interface {
	// ClickHouse
	BatchInsertStats(context.Context, *BatchInsertStatsReq) (*emptypb.Empty, error)
	IncreaseUserRequests(context.Context, *IncreaseUserRequestsReq) (*emptypb.Empty, error)
	// PosgreSQL
	GetAllUsers(*emptypb.Empty, grpc.ServerStreamingServer[GetUserInfoResp]) error
	GetUserInfo(grpc.BidiStreamingServer[GetUserInfoReq, GetUserInfoResp]) error
	GetSubscriptions(context.Context, *emptypb.Empty) (*GetSubscriptionsResp, error)
	mustEmbedUnimplementedAuraServer()
}

// UnimplementedAuraServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuraServer struct{}

func (UnimplementedAuraServer) BatchInsertStats(context.Context, *BatchInsertStatsReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchInsertStats not implemented")
}
func (UnimplementedAuraServer) IncreaseUserRequests(context.Context, *IncreaseUserRequestsReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncreaseUserRequests not implemented")
}
func (UnimplementedAuraServer) GetAllUsers(*emptypb.Empty, grpc.ServerStreamingServer[GetUserInfoResp]) error {
	return status.Errorf(codes.Unimplemented, "method GetAllUsers not implemented")
}
func (UnimplementedAuraServer) GetUserInfo(grpc.BidiStreamingServer[GetUserInfoReq, GetUserInfoResp]) error {
	return status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedAuraServer) GetSubscriptions(context.Context, *emptypb.Empty) (*GetSubscriptionsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscriptions not implemented")
}
func (UnimplementedAuraServer) mustEmbedUnimplementedAuraServer() {}
func (UnimplementedAuraServer) testEmbeddedByValue()              {}

// UnsafeAuraServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuraServer will
// result in compilation errors.
type UnsafeAuraServer interface {
	mustEmbedUnimplementedAuraServer()
}

func RegisterAuraServer(s grpc.ServiceRegistrar, srv AuraServer) {
	// If the following call pancis, it indicates UnimplementedAuraServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Aura_ServiceDesc, srv)
}

func _Aura_BatchInsertStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchInsertStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuraServer).BatchInsertStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aura_BatchInsertStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuraServer).BatchInsertStats(ctx, req.(*BatchInsertStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aura_IncreaseUserRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncreaseUserRequestsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuraServer).IncreaseUserRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aura_IncreaseUserRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuraServer).IncreaseUserRequests(ctx, req.(*IncreaseUserRequestsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aura_GetAllUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuraServer).GetAllUsers(m, &grpc.GenericServerStream[emptypb.Empty, GetUserInfoResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Aura_GetAllUsersServer = grpc.ServerStreamingServer[GetUserInfoResp]

func _Aura_GetUserInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AuraServer).GetUserInfo(&grpc.GenericServerStream[GetUserInfoReq, GetUserInfoResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Aura_GetUserInfoServer = grpc.BidiStreamingServer[GetUserInfoReq, GetUserInfoResp]

func _Aura_GetSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuraServer).GetSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aura_GetSubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuraServer).GetSubscriptions(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Aura_ServiceDesc is the grpc.ServiceDesc for Aura service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Aura_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Aura",
	HandlerType: (*AuraServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchInsertStats",
			Handler:    _Aura_BatchInsertStats_Handler,
		},
		{
			MethodName: "IncreaseUserRequests",
			Handler:    _Aura_IncreaseUserRequests_Handler,
		},
		{
			MethodName: "GetSubscriptions",
			Handler:    _Aura_GetSubscriptions_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllUsers",
			Handler:       _Aura_GetAllUsers_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetUserInfo",
			Handler:       _Aura_GetUserInfo_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/aura.proto",
}
