syntax = "proto3";

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

option go_package = "aura-api/pkg/proto";

package proto;

service Aura {
  // ClickHouse
  rpc BatchInsertStats(BatchInsertStatsReq) returns (google.protobuf.Empty) {}
  rpc IncreaseUserRequests(IncreaseUserRequestsReq) returns (google.protobuf.Empty) {}
  // PosgreSQL
  rpc GetUserInfo(GetUserInfoReq) returns (GetUserInfoResp) {}
  rpc GetSubscriptions(google.protobuf.Empty) returns (GetSubscriptionsResp) {}
}

message Stat {
  google.protobuf.Timestamp timestamp = 1;
  string user_uid = 2;
  string request_uuid = 3;
  string endpoint = 4;
  string rpc_error_code = 5;
  string user_agent = 6;
  string rpc_method = 7;
  string rpc_request_data = 8;
  string chain = 9;
  int64 execution_time_ms = 10;
  int64 response_time_ms = 11;
  uint32 status = 12;
  uint32 attempts = 13;
  string token_uuid = 14;
  int64 response_size_bytes = 15;
  string target_type = 16;
  string provider = 17;
  int64 method_cost = 18;
  bool is_mainnet = 19;
  int64 subscription_id = 20;
}

message BatchInsertStatsReq {
  repeated Stat stats = 1;
}

message IncreaseUserRequestsReq {
  map<string, UserRequestsByChain> reqs = 1;
}

message UserRequestsByChain {
  map<string, UserRequestsByToken> reqs = 1;
}

message UserRequestsByToken {
  map<string, RequestsWithUsage> reqs = 1;
}

message RequestsWithUsage {
  int64 reqs = 1;
  int64 usage = 2;
  bool is_mainnet = 3;
}

message GetUserInfoReq {
  string api_token = 1;
}
message GetUserInfoResp {
  UserWithTokens user = 1;
}
message UserWithTokens {
  string user = 1;
  int64 subscription_id = 2;
  int64 mplx_balance = 3;
  google.protobuf.Timestamp subscription_ends_on = 4;
  repeated string tokens = 5;
}

message PricingModel {
  int32 requests_per_second = 1;
  int64 price_mplx = 2;
}

message Pricing {
  PricingModel aura_das = 1;
  PricingModel eclipse_das = 2;
  PricingModel eclipse_rpc = 3;
  PricingModel solana_rpc = 4;
  PricingModel get_program_accounts = 5;
  PricingModel solana_swqos = 6;
  PricingModel websocket = 7;
  int64 monthly_price_mplx = 8;
}

message SubscriptionWithPricing {
  int64 id = 1;
  string name = 2;
  int64 priority = 3;
  int64 api_tokens_limit = 4;
  bool priority_support = 5;
  Pricing pricing = 6;
}

message GetSubscriptionsResp {
  repeated SubscriptionWithPricing subscriptions = 1;
}