// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.15.8
// source: pkg/proto/aura.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Aura_BatchInsertStats_FullMethodName            = "/proto.Aura/BatchInsertStats"
	Aura_IncreaseUserRequests_FullMethodName        = "/proto.Aura/IncreaseUserRequests"
	Aura_BatchInsertDetailedRequests_FullMethodName = "/proto.Aura/BatchInsertDetailedRequests"
	Aura_GetUserInfo_FullMethodName                 = "/proto.Aura/GetUserInfo"
	Aura_GetSubscriptions_FullMethodName            = "/proto.Aura/GetSubscriptions"
)

// AuraClient is the client API for Aura service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuraClient interface {
	// ClickHouse
	BatchInsertStats(ctx context.Context, in *BatchInsertStatsReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	IncreaseUserRequests(ctx context.Context, in *IncreaseUserRequestsReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	BatchInsertDetailedRequests(ctx context.Context, in *BatchInsertDetailedRequestsReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// PosgreSQL
	GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
	GetSubscriptions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSubscriptionsResp, error)
}

type auraClient struct {
	cc grpc.ClientConnInterface
}

func NewAuraClient(cc grpc.ClientConnInterface) AuraClient {
	return &auraClient{cc}
}

func (c *auraClient) BatchInsertStats(ctx context.Context, in *BatchInsertStatsReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Aura_BatchInsertStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auraClient) IncreaseUserRequests(ctx context.Context, in *IncreaseUserRequestsReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Aura_IncreaseUserRequests_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auraClient) BatchInsertDetailedRequests(ctx context.Context, in *BatchInsertDetailedRequestsReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Aura_BatchInsertDetailedRequests_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auraClient) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	out := new(GetUserInfoResp)
	err := c.cc.Invoke(ctx, Aura_GetUserInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auraClient) GetSubscriptions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSubscriptionsResp, error) {
	out := new(GetSubscriptionsResp)
	err := c.cc.Invoke(ctx, Aura_GetSubscriptions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuraServer is the server API for Aura service.
// All implementations must embed UnimplementedAuraServer
// for forward compatibility
type AuraServer interface {
	// ClickHouse
	BatchInsertStats(context.Context, *BatchInsertStatsReq) (*emptypb.Empty, error)
	IncreaseUserRequests(context.Context, *IncreaseUserRequestsReq) (*emptypb.Empty, error)
	BatchInsertDetailedRequests(context.Context, *BatchInsertDetailedRequestsReq) (*emptypb.Empty, error)
	// PosgreSQL
	GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoResp, error)
	GetSubscriptions(context.Context, *emptypb.Empty) (*GetSubscriptionsResp, error)
	mustEmbedUnimplementedAuraServer()
}

// UnimplementedAuraServer must be embedded to have forward compatible implementations.
type UnimplementedAuraServer struct {
}

func (UnimplementedAuraServer) BatchInsertStats(context.Context, *BatchInsertStatsReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchInsertStats not implemented")
}
func (UnimplementedAuraServer) IncreaseUserRequests(context.Context, *IncreaseUserRequestsReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncreaseUserRequests not implemented")
}
func (UnimplementedAuraServer) BatchInsertDetailedRequests(context.Context, *BatchInsertDetailedRequestsReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchInsertDetailedRequests not implemented")
}
func (UnimplementedAuraServer) GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedAuraServer) GetSubscriptions(context.Context, *emptypb.Empty) (*GetSubscriptionsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscriptions not implemented")
}
func (UnimplementedAuraServer) mustEmbedUnimplementedAuraServer() {}

// UnsafeAuraServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuraServer will
// result in compilation errors.
type UnsafeAuraServer interface {
	mustEmbedUnimplementedAuraServer()
}

func RegisterAuraServer(s grpc.ServiceRegistrar, srv AuraServer) {
	s.RegisterService(&Aura_ServiceDesc, srv)
}

func _Aura_BatchInsertStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchInsertStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuraServer).BatchInsertStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aura_BatchInsertStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuraServer).BatchInsertStats(ctx, req.(*BatchInsertStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aura_IncreaseUserRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncreaseUserRequestsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuraServer).IncreaseUserRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aura_IncreaseUserRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuraServer).IncreaseUserRequests(ctx, req.(*IncreaseUserRequestsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aura_BatchInsertDetailedRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchInsertDetailedRequestsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuraServer).BatchInsertDetailedRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aura_BatchInsertDetailedRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuraServer).BatchInsertDetailedRequests(ctx, req.(*BatchInsertDetailedRequestsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aura_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuraServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aura_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuraServer).GetUserInfo(ctx, req.(*GetUserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Aura_GetSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuraServer).GetSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aura_GetSubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuraServer).GetSubscriptions(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Aura_ServiceDesc is the grpc.ServiceDesc for Aura service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Aura_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Aura",
	HandlerType: (*AuraServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchInsertStats",
			Handler:    _Aura_BatchInsertStats_Handler,
		},
		{
			MethodName: "IncreaseUserRequests",
			Handler:    _Aura_IncreaseUserRequests_Handler,
		},
		{
			MethodName: "BatchInsertDetailedRequests",
			Handler:    _Aura_BatchInsertDetailedRequests_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _Aura_GetUserInfo_Handler,
		},
		{
			MethodName: "GetSubscriptions",
			Handler:    _Aura_GetSubscriptions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/aura.proto",
}
